name: spooky_ai
description: "🎃 SpookyAI - AI-Powered Halloween Image Generator. Transform your photos into spooky Halloween masterpieces with the power of AI!"
publish_to: 'none'

# Version: Major.Minor.Patch+Build
# Major: Breaking changes
# Minor: New features, backward compatible  
# Patch: Bug fixes, backward compatible
# Build: Incremental build number
version: 1.0.0+9

environment:
  sdk: ^3.10.0-158.0.dev

# Core Dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # HTTP & Networking
  http: ^1.2.2
  
  # Image & Media
  image_picker: ^1.0.7
  gal: ^2.3.0
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2
  
  # Permissions & System
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.0
  
  # Sharing & Social
  share_plus: ^10.0.2
  
  # Animations
  lottie: ^3.1.2
  
  # State Management
  provider: ^6.1.2
  
  # In-App Purchases
  in_app_purchase: ^3.1.13
  in_app_purchase_android: ^0.4.0
  in_app_purchase_storekit: ^0.3.7
  
  # Quick Actions (App Shortcuts)
  quick_actions: ^1.1.0
  
  # URL Launcher
  url_launcher: ^6.2.4
  
  # Environment Variables
  flutter_dotenv: ^5.1.0

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Quality
  flutter_lints: ^6.0.0
  
  # App Icons
  flutter_launcher_icons: ^0.13.1

# Flutter Configuration
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/ss/
    - .env

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#0F0B1A"
  remove_alpha_ios: true